### ISSUE TITLE
Colored noise using jupyter notebook on Mac?

### ISSUE THREAD

**Issue by Sherifa96** [japilo/colorednoise#2]
Hi! I'm trying to install the package on my jupyter notebook and get this error:
also installing the dependencies ‘Rcpp’, ‘data.table’, ‘RcppArmadillo’

Warning message in install.packages("colorednoise"):
“installation of package ‘Rcpp’ had non-zero exit status”Warning message in install.packages("colorednoise"):
“installation of package ‘data.table’ had non-zero exit status”Warning message in install.packages("colorednoise"):
“installation of package ‘RcppArmadillo’ had non-zero exit status”Warning message in install.packages("colorednoise"):
“installation of package ‘colorednoise’ had non-zero exit status”Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

Any clue what this could be due to? I have tried googling but nothing works

**Comment by japilo** [comment]
Interesting. I've never tried to install the package inside of a jupyter notebook before, but given the dependency packages that are throwing errors, I'm willing to bet it's an issue with C compiling. Can you install some kind of tool with in the notebook for compiling C code?

**Comment by Sherifa96** [comment]
Hey! So I needed to use an older version of your package to get it going to the jupyter notebook. 
to solve the issue with the data table i needed to manually install data.table with the following code: #install.packages("data.table", type="source", repos="https://Rdatatable.gitlab.io/data.table")
Unfortunately the Rccp package connected to your current version of colorednoise won't install on the current version of R connected to the Jupyter which I can't seem to update. So I installed an older version of your package which then worked :) 
#require(devtools)
#install_version("colorednoise", version = "1.0.3", repos = "http://cran.us.r-project.org")

I guess that would be one way around until the most uptodate version of R is available to be connected to jupyter notebook.
